version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - develop
init:
  # Good practice, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore --verbosity m
build_script:
  # output will be in /.src/{YOUR_PROJECT_DIR}/bin/Debug/netcoreapp2.1/publish/
  - cmd: dotnet publish ./*/*.csproj
artifacts:
#  - path: test.zip
 - path: '\Fpa.Servers.WebApi\bin\Debug\netcoreapp2.2\publish\'
   name: WebApi
#   type: WebDeployPackage
clone_depth: 1
on_finish :
  # any cleanup in here
deploy:
  provider: WebDeploy
  server: https://kloder.ru:8172/msdeploy.axd
  website: api
  username: Administrator
  password: HXS7atqd
  ntlm: false
  remove_files: false
  artifact:
